/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 19
#define LARGE_STATE_COUNT 18
#define SYMBOL_COUNT 32
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LPAREN = 1,
  anon_sym_RPAREN = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  sym_exclaim_prefix = 5,
  sym_question_prefix = 6,
  sym_quote_prefix = 7,
  sym_variable = 8,
  sym_wildcard = 9,
  anon_sym_True = 10,
  anon_sym_False = 11,
  sym_identifier = 12,
  sym_arrow_operator = 13,
  sym_comparison_operator = 14,
  sym_assignment_operator = 15,
  sym_punctuation_operator = 16,
  sym_arithmetic_operator = 17,
  sym_logic_operator = 18,
  sym_string_literal = 19,
  sym_integer_literal = 20,
  sym_line_comment = 21,
  sym_block_comment = 22,
  sym_source_file = 23,
  sym_expression = 24,
  sym_list = 25,
  sym_brace_list = 26,
  sym_prefixed_expression = 27,
  sym_atom_expression = 28,
  sym_boolean_literal = 29,
  sym_operator = 30,
  aux_sym_source_file_repeat1 = 31,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_exclaim_prefix] = "exclaim_prefix",
  [sym_question_prefix] = "question_prefix",
  [sym_quote_prefix] = "quote_prefix",
  [sym_variable] = "variable",
  [sym_wildcard] = "wildcard",
  [anon_sym_True] = "True",
  [anon_sym_False] = "False",
  [sym_identifier] = "identifier",
  [sym_arrow_operator] = "arrow_operator",
  [sym_comparison_operator] = "comparison_operator",
  [sym_assignment_operator] = "assignment_operator",
  [sym_punctuation_operator] = "punctuation_operator",
  [sym_arithmetic_operator] = "arithmetic_operator",
  [sym_logic_operator] = "logic_operator",
  [sym_string_literal] = "string_literal",
  [sym_integer_literal] = "integer_literal",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym_expression] = "expression",
  [sym_list] = "list",
  [sym_brace_list] = "brace_list",
  [sym_prefixed_expression] = "prefixed_expression",
  [sym_atom_expression] = "atom_expression",
  [sym_boolean_literal] = "boolean_literal",
  [sym_operator] = "operator",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_exclaim_prefix] = sym_exclaim_prefix,
  [sym_question_prefix] = sym_question_prefix,
  [sym_quote_prefix] = sym_quote_prefix,
  [sym_variable] = sym_variable,
  [sym_wildcard] = sym_wildcard,
  [anon_sym_True] = anon_sym_True,
  [anon_sym_False] = anon_sym_False,
  [sym_identifier] = sym_identifier,
  [sym_arrow_operator] = sym_arrow_operator,
  [sym_comparison_operator] = sym_comparison_operator,
  [sym_assignment_operator] = sym_assignment_operator,
  [sym_punctuation_operator] = sym_punctuation_operator,
  [sym_arithmetic_operator] = sym_arithmetic_operator,
  [sym_logic_operator] = sym_logic_operator,
  [sym_string_literal] = sym_string_literal,
  [sym_integer_literal] = sym_integer_literal,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym_expression] = sym_expression,
  [sym_list] = sym_list,
  [sym_brace_list] = sym_brace_list,
  [sym_prefixed_expression] = sym_prefixed_expression,
  [sym_atom_expression] = sym_atom_expression,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_operator] = sym_operator,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_exclaim_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_question_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_quote_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_wildcard] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_True] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_False] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_arrow_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_comparison_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_punctuation_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_arithmetic_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_logic_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym_brace_list] = {
    .visible = true,
    .named = true,
  },
  [sym_prefixed_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_atom_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_argument = 1,
  field_prefix = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_argument] = "argument",
  [field_prefix] = "prefix",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_argument, 1},
    {field_prefix, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '!', 13,
        '"', 1,
        '$', 16,
        '&', 6,
        '\'', 15,
        '(', 9,
        ')', 10,
        '-', 34,
        '.', 32,
        '/', 33,
        ';', 40,
        '<', 29,
        '=', 30,
        '>', 28,
        '?', 14,
        'F', 20,
        'T', 23,
        '_', 17,
        '{', 11,
        '}', 12,
        '*', 35,
        '+', 35,
        ',', 31,
        ':', 31,
        '@', 31,
        '|', 31,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(37);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(27);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(31);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(41);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 6:
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 7:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_exclaim_prefix);
      if (lookahead == '?') ADVANCE(36);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_question_prefix);
      if (lookahead == '!') ADVANCE(36);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_quote_prefix);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_variable);
      if (lookahead == '&' ||
          lookahead == '\'' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_wildcard);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '*') ADVANCE(19);
      if (lookahead == '\'' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '/') ADVANCE(41);
      if (lookahead == '\'' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(18);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(22);
      if (lookahead == '\'' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(26);
      if (lookahead == '\'' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(24);
      if (lookahead == '\'' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(25);
      if (lookahead == '\'' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(21);
      if (lookahead == '\'' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(21);
      if (lookahead == '\'' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '\'' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_arrow_operator);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_comparison_operator);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_comparison_operator);
      if (lookahead == '<') ADVANCE(3);
      if (lookahead == '-' ||
          lookahead == '=') ADVANCE(27);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_assignment_operator);
      if (lookahead == '=') ADVANCE(28);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_punctuation_operator);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_punctuation_operator);
      if (lookahead == '.') ADVANCE(4);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_arithmetic_operator);
      if (lookahead == '*') ADVANCE(18);
      if (lookahead == '/') ADVANCE(39);
      if (lookahead == '\'' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_arithmetic_operator);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      if (lookahead == '\'' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          lookahead == '/' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_arithmetic_operator);
      if (lookahead == '\'' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(26);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_logic_operator);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_string_literal);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_integer_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '\'' ||
          lookahead == '*' ||
          lookahead == '+' ||
          lookahead == '-' ||
          ('/' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_exclaim_prefix] = ACTIONS(1),
    [sym_question_prefix] = ACTIONS(1),
    [sym_quote_prefix] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
    [sym_wildcard] = ACTIONS(1),
    [anon_sym_True] = ACTIONS(1),
    [anon_sym_False] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_arrow_operator] = ACTIONS(1),
    [sym_comparison_operator] = ACTIONS(1),
    [sym_assignment_operator] = ACTIONS(1),
    [sym_punctuation_operator] = ACTIONS(1),
    [sym_arithmetic_operator] = ACTIONS(1),
    [sym_logic_operator] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [sym_expression] = STATE(5),
    [sym_list] = STATE(12),
    [sym_brace_list] = STATE(12),
    [sym_prefixed_expression] = STATE(12),
    [sym_atom_expression] = STATE(12),
    [sym_boolean_literal] = STATE(9),
    [sym_operator] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_exclaim_prefix] = ACTIONS(11),
    [sym_question_prefix] = ACTIONS(11),
    [sym_quote_prefix] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_wildcard] = ACTIONS(13),
    [anon_sym_True] = ACTIONS(15),
    [anon_sym_False] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_arrow_operator] = ACTIONS(19),
    [sym_comparison_operator] = ACTIONS(19),
    [sym_assignment_operator] = ACTIONS(19),
    [sym_punctuation_operator] = ACTIONS(19),
    [sym_arithmetic_operator] = ACTIONS(19),
    [sym_logic_operator] = ACTIONS(21),
    [sym_string_literal] = ACTIONS(13),
    [sym_integer_literal] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_expression] = STATE(2),
    [sym_list] = STATE(12),
    [sym_brace_list] = STATE(12),
    [sym_prefixed_expression] = STATE(12),
    [sym_atom_expression] = STATE(12),
    [sym_boolean_literal] = STATE(9),
    [sym_operator] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_LPAREN] = ACTIONS(25),
    [anon_sym_RPAREN] = ACTIONS(23),
    [anon_sym_LBRACE] = ACTIONS(28),
    [anon_sym_RBRACE] = ACTIONS(23),
    [sym_exclaim_prefix] = ACTIONS(31),
    [sym_question_prefix] = ACTIONS(31),
    [sym_quote_prefix] = ACTIONS(31),
    [sym_variable] = ACTIONS(34),
    [sym_wildcard] = ACTIONS(34),
    [anon_sym_True] = ACTIONS(37),
    [anon_sym_False] = ACTIONS(37),
    [sym_identifier] = ACTIONS(40),
    [sym_arrow_operator] = ACTIONS(43),
    [sym_comparison_operator] = ACTIONS(43),
    [sym_assignment_operator] = ACTIONS(43),
    [sym_punctuation_operator] = ACTIONS(43),
    [sym_arithmetic_operator] = ACTIONS(43),
    [sym_logic_operator] = ACTIONS(46),
    [sym_string_literal] = ACTIONS(34),
    [sym_integer_literal] = ACTIONS(34),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym_expression] = STATE(6),
    [sym_list] = STATE(12),
    [sym_brace_list] = STATE(12),
    [sym_prefixed_expression] = STATE(12),
    [sym_atom_expression] = STATE(12),
    [sym_boolean_literal] = STATE(9),
    [sym_operator] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(6),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(49),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_exclaim_prefix] = ACTIONS(11),
    [sym_question_prefix] = ACTIONS(11),
    [sym_quote_prefix] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_wildcard] = ACTIONS(13),
    [anon_sym_True] = ACTIONS(15),
    [anon_sym_False] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_arrow_operator] = ACTIONS(19),
    [sym_comparison_operator] = ACTIONS(19),
    [sym_assignment_operator] = ACTIONS(19),
    [sym_punctuation_operator] = ACTIONS(19),
    [sym_arithmetic_operator] = ACTIONS(19),
    [sym_logic_operator] = ACTIONS(21),
    [sym_string_literal] = ACTIONS(13),
    [sym_integer_literal] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [sym_expression] = STATE(7),
    [sym_list] = STATE(12),
    [sym_brace_list] = STATE(12),
    [sym_prefixed_expression] = STATE(12),
    [sym_atom_expression] = STATE(12),
    [sym_boolean_literal] = STATE(9),
    [sym_operator] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(7),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(51),
    [sym_exclaim_prefix] = ACTIONS(11),
    [sym_question_prefix] = ACTIONS(11),
    [sym_quote_prefix] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_wildcard] = ACTIONS(13),
    [anon_sym_True] = ACTIONS(15),
    [anon_sym_False] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_arrow_operator] = ACTIONS(19),
    [sym_comparison_operator] = ACTIONS(19),
    [sym_assignment_operator] = ACTIONS(19),
    [sym_punctuation_operator] = ACTIONS(19),
    [sym_arithmetic_operator] = ACTIONS(19),
    [sym_logic_operator] = ACTIONS(21),
    [sym_string_literal] = ACTIONS(13),
    [sym_integer_literal] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [sym_expression] = STATE(2),
    [sym_list] = STATE(12),
    [sym_brace_list] = STATE(12),
    [sym_prefixed_expression] = STATE(12),
    [sym_atom_expression] = STATE(12),
    [sym_boolean_literal] = STATE(9),
    [sym_operator] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(53),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_exclaim_prefix] = ACTIONS(11),
    [sym_question_prefix] = ACTIONS(11),
    [sym_quote_prefix] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_wildcard] = ACTIONS(13),
    [anon_sym_True] = ACTIONS(15),
    [anon_sym_False] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_arrow_operator] = ACTIONS(19),
    [sym_comparison_operator] = ACTIONS(19),
    [sym_assignment_operator] = ACTIONS(19),
    [sym_punctuation_operator] = ACTIONS(19),
    [sym_arithmetic_operator] = ACTIONS(19),
    [sym_logic_operator] = ACTIONS(21),
    [sym_string_literal] = ACTIONS(13),
    [sym_integer_literal] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [sym_expression] = STATE(2),
    [sym_list] = STATE(12),
    [sym_brace_list] = STATE(12),
    [sym_prefixed_expression] = STATE(12),
    [sym_atom_expression] = STATE(12),
    [sym_boolean_literal] = STATE(9),
    [sym_operator] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_RPAREN] = ACTIONS(55),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_exclaim_prefix] = ACTIONS(11),
    [sym_question_prefix] = ACTIONS(11),
    [sym_quote_prefix] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_wildcard] = ACTIONS(13),
    [anon_sym_True] = ACTIONS(15),
    [anon_sym_False] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_arrow_operator] = ACTIONS(19),
    [sym_comparison_operator] = ACTIONS(19),
    [sym_assignment_operator] = ACTIONS(19),
    [sym_punctuation_operator] = ACTIONS(19),
    [sym_arithmetic_operator] = ACTIONS(19),
    [sym_logic_operator] = ACTIONS(21),
    [sym_string_literal] = ACTIONS(13),
    [sym_integer_literal] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [sym_expression] = STATE(2),
    [sym_list] = STATE(12),
    [sym_brace_list] = STATE(12),
    [sym_prefixed_expression] = STATE(12),
    [sym_atom_expression] = STATE(12),
    [sym_boolean_literal] = STATE(9),
    [sym_operator] = STATE(9),
    [aux_sym_source_file_repeat1] = STATE(2),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_RBRACE] = ACTIONS(57),
    [sym_exclaim_prefix] = ACTIONS(11),
    [sym_question_prefix] = ACTIONS(11),
    [sym_quote_prefix] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_wildcard] = ACTIONS(13),
    [anon_sym_True] = ACTIONS(15),
    [anon_sym_False] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_arrow_operator] = ACTIONS(19),
    [sym_comparison_operator] = ACTIONS(19),
    [sym_assignment_operator] = ACTIONS(19),
    [sym_punctuation_operator] = ACTIONS(19),
    [sym_arithmetic_operator] = ACTIONS(19),
    [sym_logic_operator] = ACTIONS(21),
    [sym_string_literal] = ACTIONS(13),
    [sym_integer_literal] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [sym_expression] = STATE(15),
    [sym_list] = STATE(12),
    [sym_brace_list] = STATE(12),
    [sym_prefixed_expression] = STATE(12),
    [sym_atom_expression] = STATE(12),
    [sym_boolean_literal] = STATE(9),
    [sym_operator] = STATE(9),
    [anon_sym_LPAREN] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [sym_exclaim_prefix] = ACTIONS(11),
    [sym_question_prefix] = ACTIONS(11),
    [sym_quote_prefix] = ACTIONS(11),
    [sym_variable] = ACTIONS(13),
    [sym_wildcard] = ACTIONS(13),
    [anon_sym_True] = ACTIONS(15),
    [anon_sym_False] = ACTIONS(15),
    [sym_identifier] = ACTIONS(17),
    [sym_arrow_operator] = ACTIONS(19),
    [sym_comparison_operator] = ACTIONS(19),
    [sym_assignment_operator] = ACTIONS(19),
    [sym_punctuation_operator] = ACTIONS(19),
    [sym_arithmetic_operator] = ACTIONS(19),
    [sym_logic_operator] = ACTIONS(21),
    [sym_string_literal] = ACTIONS(13),
    [sym_integer_literal] = ACTIONS(13),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(59),
    [anon_sym_LPAREN] = ACTIONS(59),
    [anon_sym_RPAREN] = ACTIONS(59),
    [anon_sym_LBRACE] = ACTIONS(59),
    [anon_sym_RBRACE] = ACTIONS(59),
    [sym_exclaim_prefix] = ACTIONS(61),
    [sym_question_prefix] = ACTIONS(61),
    [sym_quote_prefix] = ACTIONS(61),
    [sym_variable] = ACTIONS(59),
    [sym_wildcard] = ACTIONS(59),
    [anon_sym_True] = ACTIONS(61),
    [anon_sym_False] = ACTIONS(61),
    [sym_identifier] = ACTIONS(61),
    [sym_arrow_operator] = ACTIONS(61),
    [sym_comparison_operator] = ACTIONS(61),
    [sym_assignment_operator] = ACTIONS(61),
    [sym_punctuation_operator] = ACTIONS(61),
    [sym_arithmetic_operator] = ACTIONS(61),
    [sym_logic_operator] = ACTIONS(59),
    [sym_string_literal] = ACTIONS(59),
    [sym_integer_literal] = ACTIONS(59),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(63),
    [anon_sym_RPAREN] = ACTIONS(63),
    [anon_sym_LBRACE] = ACTIONS(63),
    [anon_sym_RBRACE] = ACTIONS(63),
    [sym_exclaim_prefix] = ACTIONS(65),
    [sym_question_prefix] = ACTIONS(65),
    [sym_quote_prefix] = ACTIONS(65),
    [sym_variable] = ACTIONS(63),
    [sym_wildcard] = ACTIONS(63),
    [anon_sym_True] = ACTIONS(65),
    [anon_sym_False] = ACTIONS(65),
    [sym_identifier] = ACTIONS(65),
    [sym_arrow_operator] = ACTIONS(65),
    [sym_comparison_operator] = ACTIONS(65),
    [sym_assignment_operator] = ACTIONS(65),
    [sym_punctuation_operator] = ACTIONS(65),
    [sym_arithmetic_operator] = ACTIONS(65),
    [sym_logic_operator] = ACTIONS(63),
    [sym_string_literal] = ACTIONS(63),
    [sym_integer_literal] = ACTIONS(63),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(67),
    [anon_sym_LPAREN] = ACTIONS(67),
    [anon_sym_RPAREN] = ACTIONS(67),
    [anon_sym_LBRACE] = ACTIONS(67),
    [anon_sym_RBRACE] = ACTIONS(67),
    [sym_exclaim_prefix] = ACTIONS(69),
    [sym_question_prefix] = ACTIONS(69),
    [sym_quote_prefix] = ACTIONS(69),
    [sym_variable] = ACTIONS(67),
    [sym_wildcard] = ACTIONS(67),
    [anon_sym_True] = ACTIONS(69),
    [anon_sym_False] = ACTIONS(69),
    [sym_identifier] = ACTIONS(69),
    [sym_arrow_operator] = ACTIONS(69),
    [sym_comparison_operator] = ACTIONS(69),
    [sym_assignment_operator] = ACTIONS(69),
    [sym_punctuation_operator] = ACTIONS(69),
    [sym_arithmetic_operator] = ACTIONS(69),
    [sym_logic_operator] = ACTIONS(67),
    [sym_string_literal] = ACTIONS(67),
    [sym_integer_literal] = ACTIONS(67),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(12)] = {
    [ts_builtin_sym_end] = ACTIONS(71),
    [anon_sym_LPAREN] = ACTIONS(71),
    [anon_sym_RPAREN] = ACTIONS(71),
    [anon_sym_LBRACE] = ACTIONS(71),
    [anon_sym_RBRACE] = ACTIONS(71),
    [sym_exclaim_prefix] = ACTIONS(73),
    [sym_question_prefix] = ACTIONS(73),
    [sym_quote_prefix] = ACTIONS(73),
    [sym_variable] = ACTIONS(71),
    [sym_wildcard] = ACTIONS(71),
    [anon_sym_True] = ACTIONS(73),
    [anon_sym_False] = ACTIONS(73),
    [sym_identifier] = ACTIONS(73),
    [sym_arrow_operator] = ACTIONS(73),
    [sym_comparison_operator] = ACTIONS(73),
    [sym_assignment_operator] = ACTIONS(73),
    [sym_punctuation_operator] = ACTIONS(73),
    [sym_arithmetic_operator] = ACTIONS(73),
    [sym_logic_operator] = ACTIONS(71),
    [sym_string_literal] = ACTIONS(71),
    [sym_integer_literal] = ACTIONS(71),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(13)] = {
    [ts_builtin_sym_end] = ACTIONS(75),
    [anon_sym_LPAREN] = ACTIONS(75),
    [anon_sym_RPAREN] = ACTIONS(75),
    [anon_sym_LBRACE] = ACTIONS(75),
    [anon_sym_RBRACE] = ACTIONS(75),
    [sym_exclaim_prefix] = ACTIONS(77),
    [sym_question_prefix] = ACTIONS(77),
    [sym_quote_prefix] = ACTIONS(77),
    [sym_variable] = ACTIONS(75),
    [sym_wildcard] = ACTIONS(75),
    [anon_sym_True] = ACTIONS(77),
    [anon_sym_False] = ACTIONS(77),
    [sym_identifier] = ACTIONS(77),
    [sym_arrow_operator] = ACTIONS(77),
    [sym_comparison_operator] = ACTIONS(77),
    [sym_assignment_operator] = ACTIONS(77),
    [sym_punctuation_operator] = ACTIONS(77),
    [sym_arithmetic_operator] = ACTIONS(77),
    [sym_logic_operator] = ACTIONS(75),
    [sym_string_literal] = ACTIONS(75),
    [sym_integer_literal] = ACTIONS(75),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(14)] = {
    [ts_builtin_sym_end] = ACTIONS(79),
    [anon_sym_LPAREN] = ACTIONS(79),
    [anon_sym_RPAREN] = ACTIONS(79),
    [anon_sym_LBRACE] = ACTIONS(79),
    [anon_sym_RBRACE] = ACTIONS(79),
    [sym_exclaim_prefix] = ACTIONS(81),
    [sym_question_prefix] = ACTIONS(81),
    [sym_quote_prefix] = ACTIONS(81),
    [sym_variable] = ACTIONS(79),
    [sym_wildcard] = ACTIONS(79),
    [anon_sym_True] = ACTIONS(81),
    [anon_sym_False] = ACTIONS(81),
    [sym_identifier] = ACTIONS(81),
    [sym_arrow_operator] = ACTIONS(81),
    [sym_comparison_operator] = ACTIONS(81),
    [sym_assignment_operator] = ACTIONS(81),
    [sym_punctuation_operator] = ACTIONS(81),
    [sym_arithmetic_operator] = ACTIONS(81),
    [sym_logic_operator] = ACTIONS(79),
    [sym_string_literal] = ACTIONS(79),
    [sym_integer_literal] = ACTIONS(79),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(15)] = {
    [ts_builtin_sym_end] = ACTIONS(83),
    [anon_sym_LPAREN] = ACTIONS(83),
    [anon_sym_RPAREN] = ACTIONS(83),
    [anon_sym_LBRACE] = ACTIONS(83),
    [anon_sym_RBRACE] = ACTIONS(83),
    [sym_exclaim_prefix] = ACTIONS(85),
    [sym_question_prefix] = ACTIONS(85),
    [sym_quote_prefix] = ACTIONS(85),
    [sym_variable] = ACTIONS(83),
    [sym_wildcard] = ACTIONS(83),
    [anon_sym_True] = ACTIONS(85),
    [anon_sym_False] = ACTIONS(85),
    [sym_identifier] = ACTIONS(85),
    [sym_arrow_operator] = ACTIONS(85),
    [sym_comparison_operator] = ACTIONS(85),
    [sym_assignment_operator] = ACTIONS(85),
    [sym_punctuation_operator] = ACTIONS(85),
    [sym_arithmetic_operator] = ACTIONS(85),
    [sym_logic_operator] = ACTIONS(83),
    [sym_string_literal] = ACTIONS(83),
    [sym_integer_literal] = ACTIONS(83),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(16)] = {
    [ts_builtin_sym_end] = ACTIONS(87),
    [anon_sym_LPAREN] = ACTIONS(87),
    [anon_sym_RPAREN] = ACTIONS(87),
    [anon_sym_LBRACE] = ACTIONS(87),
    [anon_sym_RBRACE] = ACTIONS(87),
    [sym_exclaim_prefix] = ACTIONS(89),
    [sym_question_prefix] = ACTIONS(89),
    [sym_quote_prefix] = ACTIONS(89),
    [sym_variable] = ACTIONS(87),
    [sym_wildcard] = ACTIONS(87),
    [anon_sym_True] = ACTIONS(89),
    [anon_sym_False] = ACTIONS(89),
    [sym_identifier] = ACTIONS(89),
    [sym_arrow_operator] = ACTIONS(89),
    [sym_comparison_operator] = ACTIONS(89),
    [sym_assignment_operator] = ACTIONS(89),
    [sym_punctuation_operator] = ACTIONS(89),
    [sym_arithmetic_operator] = ACTIONS(89),
    [sym_logic_operator] = ACTIONS(87),
    [sym_string_literal] = ACTIONS(87),
    [sym_integer_literal] = ACTIONS(87),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(17)] = {
    [ts_builtin_sym_end] = ACTIONS(91),
    [anon_sym_LPAREN] = ACTIONS(91),
    [anon_sym_RPAREN] = ACTIONS(91),
    [anon_sym_LBRACE] = ACTIONS(91),
    [anon_sym_RBRACE] = ACTIONS(91),
    [sym_exclaim_prefix] = ACTIONS(93),
    [sym_question_prefix] = ACTIONS(93),
    [sym_quote_prefix] = ACTIONS(93),
    [sym_variable] = ACTIONS(91),
    [sym_wildcard] = ACTIONS(91),
    [anon_sym_True] = ACTIONS(93),
    [anon_sym_False] = ACTIONS(93),
    [sym_identifier] = ACTIONS(93),
    [sym_arrow_operator] = ACTIONS(93),
    [sym_comparison_operator] = ACTIONS(93),
    [sym_assignment_operator] = ACTIONS(93),
    [sym_punctuation_operator] = ACTIONS(93),
    [sym_arithmetic_operator] = ACTIONS(93),
    [sym_logic_operator] = ACTIONS(91),
    [sym_string_literal] = ACTIONS(91),
    [sym_integer_literal] = ACTIONS(91),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(18)] = 0,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_atom_expression, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_atom_expression, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_list, 2, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_list, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefixed_expression, 2, 0, 1),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_prefixed_expression, 2, 0, 1),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_brace_list, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_brace_list, 3, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_metta(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
